project_id = "dfsuptqouzhhcnwhrukg"

[functions.ask-messa]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.weather-alert-check]
verify_jwt = false

[functions.view-contract]
verify_jwt = false

[functions.generate-project-brief]
verify_jwt = false

[functions.generate-team-report]
verify_jwt = false

[functions.obc-status-check]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.external-db]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.ai-project-analysis]
verify_jwt = false

[functions.send-dna-report]
verify_jwt = false

[functions.contact-form]
verify_jwt = false

[functions.delete-project]
verify_jwt = false

[functions.waitlist-welcome]
verify_jwt = false